name = "OliveReadOnly"
uuid = "7aeabb7e-fcf6-4882-8a40-b3e2d665735e"
authors = ["emmac <emmaccode@gmail.com>"]
version = "0.1.0"

[deps]
Olive = "724ecaf6-c7a0-4c22-b37e-0bb7b4193da8"

[compat]
Olive = "0.2.4"
julia = "1.8"
